export type Locale = "zh" | "en";

/** All UI strings — keep zh/en keys in sync. */
export const STRINGS: Record<
  Locale,
  {
    appTitle: string;
    documentTitleSuffix: string;
    tagline: string;
    langZh: string;
    langEn: string;
    langAria: string;
    warnUnconfigured: string;
    cardKbTitle: string;
    rootDir: string;
    kbMetaSourcePrefix: string;
    kbSourceEnv: string;
    kbSourceUser: string;
    kbSourceDefault: string;
    kbMetaCustomPath: string;
    kbMetaEnvLocked: string;
    kbMetaNotesLocation: string;
    kbPathLabel: string;
    placeholderVault: string;
    btnSave: string;
    btnSaving: string;
    btnResetDefault: string;
    kbSaveOk: string;
    kbResetOk: string;
    errNetwork: string;
    errSaveFailed: string;
    errResetFailed: string;
    btnMaintain: string;
    btnMaintaining: string;
    badgeNotesCount: string;
    badgeLastMaintained: string;
    badgeNoMaintenanceYet: string;
    warnStub: string;
    uploadSection: string;
    choosePhoto: string;
    processing: string;
    hintPhoto: string;
    resultSection: string;
    taskId: string;
    savedToKb: string;
    viewMarkdownSource: string;
    noMarkdown: string;
    emptyUpload: string;
    statusPending: string;
    statusProcessing: string;
    statusDone: string;
    statusFailed: string;
    processingMsg: string;
  }
> = {
  zh: {
    appTitle: "Tomato Notes2KB",
    documentTitleSuffix: "手写笔记 → Markdown",
    tagline:
      "上传手写笔记照片，由 LLM 转为 Markdown，并保存到本机个人知识库目录；后台定期整理索引。",
    langZh: "中文",
    langEn: "English",
    langAria: "界面语言",
    warnUnconfigured:
      "当前后端未配置识别服务：请在 backend/.env 中设置 OPENROUTER_API_KEY（推荐）或 OPENAI_API_KEY，重启 API 后再上传。联调 UI 可设 TOMATO_USE_STUB=1（固定假数据）。",
    cardKbTitle: "个人知识库（本机目录）",
    rootDir: "根目录",
    kbMetaSourcePrefix: "来源：",
    kbSourceEnv: "环境变量 TOMATO_KB_DIR",
    kbSourceUser: "已保存的自定义路径",
    kbSourceDefault: "默认目录（未单独配置）",
    kbMetaCustomPath:
      "自定义路径保存在 {{path}}（在数据目录内，不包含笔记正文）。",
    kbMetaEnvLocked: "当前由环境变量锁定，请在 .env 中修改 TOMATO_KB_DIR 并重启后端。",
    kbMetaNotesLocation:
      "笔记文件位于 {{notes}}；总览与整理见根目录 {{index}}（由维护任务自动生成）。",
    kbPathLabel: "知识库根目录（本机绝对路径，可指向仓库外任意文件夹）",
    placeholderVault: "/Users/you/Documents/MyVault",
    btnSave: "保存",
    btnSaving: "保存中…",
    btnResetDefault: "恢复默认",
    kbSaveOk: "已保存。新笔记将写入该目录（可与代码仓库完全分离）。",
    kbResetOk: "已恢复为默认知识库目录。",
    errNetwork: "网络错误",
    errSaveFailed: "保存失败 ({{status}})",
    errResetFailed: "恢复失败 ({{status}})",
    btnMaintain: "立即整理知识库",
    btnMaintaining: "正在整理…",
    badgeNotesCount: "已存笔记 {{count}} 条",
    badgeLastMaintained: "最近整理",
    badgeNoMaintenanceYet: "尚未跑过整理",
    warnStub:
      "当前为占位模式（无 API Key 且 TOMATO_USE_STUB=1，或 TOMATO_FORCE_STUB=1），结果为固定示例 Markdown。配置 Key 并重启后一般会变为真实识别。",
    uploadSection: "上传笔记",
    choosePhoto: "选择照片",
    processing: "正在识别手写内容…",
    hintPhoto: "支持常见图片格式，尽量拍平、光线均匀，字迹更清晰。",
    resultSection: "识别结果",
    taskId: "任务 ID",
    savedToKb: "已写入知识库：{{path}}（相对知识库根目录）",
    viewMarkdownSource: "查看 Markdown 源码",
    noMarkdown: "未返回 Markdown 内容",
    emptyUpload: "上传一张照片开始",
    statusPending: "待处理",
    statusProcessing: "识别中",
    statusDone: "完成",
    statusFailed: "失败",
    processingMsg: "处理中…",
  },
  en: {
    appTitle: "Tomato Notes2KB",
    documentTitleSuffix: "Handwriting → Markdown",
    tagline:
      "Upload a photo of handwritten notes. An LLM converts them to Markdown and saves them to your local knowledge base; maintenance keeps the index up to date.",
    langZh: "中文",
    langEn: "English",
    langAria: "Interface language",
    warnUnconfigured:
      "Vision is not configured: set OPENROUTER_API_KEY (recommended) or OPENAI_API_KEY in backend/.env, then restart the API. For UI-only testing, use TOMATO_USE_STUB=1 (stub data).",
    cardKbTitle: "Knowledge base (local folder)",
    rootDir: "Root",
    kbMetaSourcePrefix: "Source: ",
    kbSourceEnv: "Environment variable TOMATO_KB_DIR",
    kbSourceUser: "Saved custom path",
    kbSourceDefault: "Default (no custom path)",
    kbMetaCustomPath: "Custom path is stored in {{path}} (under the data directory; note content is not stored there).",
    kbMetaEnvLocked: "Locked by environment variable. Edit TOMATO_KB_DIR in .env and restart the server.",
    kbMetaNotesLocation:
      "Notes live under {{notes}}; the overview file is {{index}} at the vault root (auto-generated by maintenance).",
    kbPathLabel: "Knowledge base root (absolute path on this machine; can be outside the repo)",
    placeholderVault: "/Users/you/Documents/MyVault",
    btnSave: "Save",
    btnSaving: "Saving…",
    btnResetDefault: "Reset to default",
    kbSaveOk: "Saved. New notes will be written here (can be outside the code repo).",
    kbResetOk: "Restored the default knowledge base folder.",
    errNetwork: "Network error",
    errSaveFailed: "Save failed ({{status}})",
    errResetFailed: "Reset failed ({{status}})",
    btnMaintain: "Run maintenance now",
    btnMaintaining: "Maintaining…",
    badgeNotesCount: "{{count}} note(s) saved",
    badgeLastMaintained: "Last maintenance",
    badgeNoMaintenanceYet: "No maintenance run yet",
    warnStub:
      "Stub mode (no API key with TOMATO_USE_STUB=1, or TOMATO_FORCE_STUB=1): fixed sample Markdown. Configure a key and restart for real recognition.",
    uploadSection: "Upload",
    choosePhoto: "Choose photo",
    processing: "Recognizing handwriting…",
    hintPhoto: "Common image formats supported. Shoot flat with even lighting for clearer text.",
    resultSection: "Result",
    taskId: "Job ID",
    savedToKb: "Saved to vault: {{path}} (relative to vault root)",
    viewMarkdownSource: "View Markdown source",
    noMarkdown: "No Markdown returned",
    emptyUpload: "Upload a photo to start",
    statusPending: "Pending",
    statusProcessing: "Processing",
    statusDone: "Done",
    statusFailed: "Failed",
    processingMsg: "Working…",
  },
};

export type MessageKey = keyof (typeof STRINGS)["zh"];

export function interpolate(template: string, vars: Record<string, string | number>): string {
  let s = template;
  for (const [k, v] of Object.entries(vars)) {
    s = s.split(`{{${k}}}`).join(String(v));
  }
  return s;
}
